config/routes.rb
Rails.application.routes.draw do

	root 'pages#home'
	get 'about', to: 'pages#about'
	get 'signup', to: 'users#new'
	resources :users, except: [:new]
	get 'login', to: 'sessions#new'
	post 'login', to: 'sessions#create'
	delete 'logout', to: 'sessions#destroy'

  # all the rest-ful routes (REST = Representational state transfer - mapping HTTP verbs (get, post, put/patch, delete) to CRUD actions)
	# resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]
	resources :articles
  resources :categories, except: [:destroy]


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
	validates :title, presence: true, length: { minimun: 6, maximum: 100 }
	validates :description, presence: true, length: { minimun: 10, maximum: 300 }
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article
  belongs_to :category

end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name

end

app/models/concerns/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25}
  validates_uniqueness_of :name

end

app/models/user.rb
class User < ApplicationRecord
	before_save { self.email = email.downcase }
	has_many :articles, dependent: :destroy	
	validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
	VALID_EMAIL_REGEX = /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i	
	validates :email, presence: true,
	 uniqueness: { case_sensitive: false },
	 length: { maximum: 105 },
	 format: {with: VALID_EMAIL_REGEX}
	 has_secure_password
	 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_user
    if !helpers.logged_in?
      flash[:danger] = "You need to be logged in to perform that action"
      redirect_to root_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController 
	before_action :set_article, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

	def show
		# byebug
	end

	def index
		@articles = Article.paginate(page: params[:page])
	end

	def new
		@article = Article.new
	end

	def edit
		
	end
	
	def create
		# render plain: params[:article]
		@article = Article.new(article_params)
		@article.user = helpers.current_user
		# render plain: @article
		if @article.save
			flash[:notice] = "Article was created successfully."
			# redirect_to article_path(@article)
			redirect_to @article
		else
			render 'new'
		end
	end

	def update
		if @article.update(article_params)
			flash[:notice] = "Article was updated successfully."
			redirect_to @article
		else
			render 'edit'
		end
	end

	def destroy		
		@article.destroy
		redirect_to articles_path
	end

	private

		def set_article
			@article = Article.find(params[:id])
		end

		def article_params
			params.require(:article).permit(:title, :description, category_ids:[])
		end

    def require_same_user
      if helpers.current_user != @article.user and !helpers.current_user.admin?
        flash[:danger] = "You cannot edit this article"
        redirect_to article_path(@article)
      end
    end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update]
  before_action :require_admin, except: [:index, :show]

  def index
    @categories = Category.paginate(page: params[:page])
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was created successfully."
      redirect_to categories_path
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @acategory.update(category_params)
      flash[:notice] = "Category was updated successfully."
      redirect_to @category
    else
      render 'edit'
    end
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page])
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end

  def set_category
      @category = Category.find(params[:id])
  end

  def require_admin
      if !helpers.logged_in? || (helpers.logged_in? and !helpers.current_user.admin?)
        flash[:danger] = "Only admins can perform that action"
        redirect_to categories_path
      end
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  
  def home
    redirect_to articles_path if helpers.logged_in?
  end
  
  def about
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
	end

	def create
		user = User.find_by(email: params[:session][:email].downcase)
		if user && user.authenticate(params[:session][:password])
			session[:user_id] = user.id
			flash[:notice] = "logged in successfully"
			redirect_to user

		else
			flash.now[:alert] ="Your login credentials were not correct"
			render 'new'
		end

	end

	def destroy
		session[:user_id] = nil
		flash[:notice] = "You successfully logged out"
		redirect_to root_path
	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :require_same_user, only: [:edit, :update]
  before_action :require_admin, only: [:destroy]

	def show
		@user_articles = @user.articles.paginate(page: params[:page])
	end

  def destroy
    @user.destroy
    flash[:danger] = "User and all articles created by user have been deleted"
    redirect_to users_path
  end

	def index
		@users = User.paginate(page: params[:page])
	end

	def new
		@user = User.new
	end

	def edit
		
	end


	def create
		@user = User.new(user_params)
		if @user.save
      session[:user_id] = @user.id
			flash[:notice] = "You have signed up to Alpha Blog #{@user.username}"
			redirect_to user_path(@user)
		else
			render 'new'
		end
	end

	def update		
		if @user.update(user_params)
			flash[:notice] = "Your account was updated successfully."
			redirect_to @user
		else
			render 'edit'
		end
	end


	private
	def user_params
		params.require(:user).permit(:username, :email, :password)
	end

	def set_user
		@user = User.find(params[:id])
	end

  def require_same_user
    if helpers.current_user != @user and !helpers.current_user.admin?
      flash[:danger] = "You cannot edit this user"
      redirect_to user_path(@user)
    end
  end

  def require_admin
    if helpers.logged_in and !helpers.current_user.admin?
      flash[:danger] = "You are not allowed to delete users"
      redirect_to users_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def gravatar_for (user, options = { size: 80 })
		email_address = user.email.downcase
		hash = Digest::MD5.hexdigest(email_address)
		size = options[:size]
		gravatar_url = "https://www.gravatar.com/avatar/#{hash}?s=#{size}"
		image_tag(gravatar_url, alt: user.username, class: "rounded mx-auto d-block")
	end

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def logged_in?
		!!current_user
	end

end

app/views/articles/_article.html.erb
<!-- possible to change @ articles for obj and parse object throug render -->
<div class="container">
	<% obj.each do |article| %>
		<div class="row justify-content-md-center">
			<div class="col-8 mt-4">
				<div class="card text-center shadow mb-5 bg-white rounded">
				  <div class="card-header font-italic">
				  	<% if article.user %>
				    by <%= link_to article.user.username, user_path(article.user) %>
				    <% end %>
				  </div>
				  <div class="card-body">
				    <h5 class="card-title"><%= link_to article.title, article_path(article), class: "text-successs" %></h5>
				    <p class="card-text"><%= truncate(article.description, length: 100) %></p>
				    <% if article.categories.any? %>
							<p>Categories: <%= render article.categories %></p>
		    		<% end %> 
				    <%= link_to "Show", article_path(article), class: "btn btn-outline-success" %>
				    <% if logged_in? && (current_user == article.user || current_user.admin?) %>
				    <%= link_to "Edit", edit_article_path(article), class: "btn btn-outline-warning" %>
				    <%= link_to "Delete", article_path(article), method: :delete, class: "btn btn-outline-danger" %>
				  <% end %>
				  </div>
				  <div class="card-footer text-muted">
				    <p><small>Created: <%= article.created_at.strftime("%d %B %Y") %>, Updated: <%= article.updated_at.strftime("%d %B %Y") %></small><br>
				    <!-- <small>Created <%= time_ago_in_words(article.created_at) %> ago, Updated <%= time_ago_in_words(article.updated_at) %> ago.</small></p> -->
				  </div>
				</div>
			</div>
		</div>
	<% end %>
</div>

app/views/articles/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @article %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @article, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :title, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.text_field :title, class: "form-control shadow rounded", placeholder: "Title" %>
          </div>
        </div>
        <div class="form-group row">
          <%= f.label :description, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.text_area :description, rows:10, class: "form-control shadow rounded", id: "exampleFormControlTextarea1", placeholder: "Description" %>      
          </div>
        </div>
        <div class="form-group">
          <div class="row justify-content-center">
            <div class="col-sm-offset-2 col-sm-8 form-check">
              <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
                <% cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
              <% end %>
            </div>
          </div>
        </div>          
        <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %> 
    </div>
    <div class="mb-3">
    <%= link_to 'Cancle and Return to listing', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/articles/edit.html.erb
<h1 class="text-center mt-5">Edit article</h1>

<%= render 'form' %>

app/views/articles/index.html.erb
<h1 class="text-center mt-5">Articles listing page</h1>

<%= render 'shared/pagination', obj: @articles %>
<%= render 'article', obj: @articles%>
<%= render 'shared/pagination', obj: @articles %>

app/views/articles/new.html.erb
<h1 class="text-center mt-5">Create new article</h1>

<%= render 'form' %>

app/views/articles/show.html.erb
<h2 class="text-center mt-5"><%= @article.title %></h1>
<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-8 mt-4">
			<div class="card text-center shadow mb-5 bg-white rounded">
				<div class="card-header font-italic">
				    by <%= @article.user.username if @article.user %>
				    <%= link_to gravatar_for(@article.user, size: 80), user_path(@article.user) %>
				</div>
		 		<div class="card-body">
		    	<div class="card-text text-left"><%= simple_format(@article.description) %></div>
		    	<% if @article.categories.any? %>
						<p>Categories: <%= render @article.categories %></p>
		    	<% end %> 
		    	<% if logged_in? && (current_user == @article.user || current_user.admin?) %>
				    <%= link_to "Edit", edit_article_path(@article), class: "btn btn-outline-warning" %>
				    <%= link_to "Delete", article_path(@article), method: :delete, class: "btn btn-outline-danger" %>
			    <% end %>
			  </div>
			  <div class="card-footer text-muted">
			    <p><small>Created: <%= @article.created_at.strftime("%d %B %Y") %>, Updated: <%= @article.updated_at.strftime("%d %B %Y") %></small><br>
				  	<small>Created <%= time_ago_in_words(@article.created_at) %> ago, Updated <%= time_ago_in_words(@article.updated_at) %> ago.</small></p>
			  </div>
			</div>
		</div>
	</div>
</div>


<%= link_to 'Return to listing', articles_path %>

app/views/categories/_category.html.erb
<span class="badge">
	<%= link_to category.name, category_path(category) %> &nbsp;
</span>

app/views/categories/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @category %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Category name" %>
          </div>
        </div>         
        <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %> 
    </div>
    <div class="mb-3">
    <%= link_to 'Cancle and Return to Categories page', categories_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<h1 class="text-center mt-5">Edit category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1 class="text-center mt-5">Categories</h1>
<div>
	<%= render 'shared/pagination', obj: @categories %>
	<% @categories.each do |category| %>
		<div class="row justify-content-md-center">
			<div class="col-4 mt-4">
				<div class="card text-center shadow mb-5 bg-white rounded">
				  <div class="card-header font-italic">
				    <%= link_to category.name, category_path(category) %>
				  </div>
				  <div class="card-footer text-muted">
				    <p><small><%= pluralize(category.articles.count, "article") %></small>
				  </div>
				</div>
			</div>
		</div>
<% end %>
<%= render 'shared/pagination', obj: @categories %>
</div>

app/views/categories/new.html.erb
<h1 class="text-center mt-5">Create new category</h1>
<div class="container">
  <%= render 'shared/errors', obj: @category %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @category, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :name, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.text_field :name, class: "form-control shadow rounded", placeholder: "Category name" %>
          </div>
        </div>         
        <div class="form-group row justify-content-center">
        <%= f.submit class: "btn btn-outline-light btn-lg" %>
        </div>
      <% end %> 
    </div>
    <div class="mb-3">
    <%= link_to 'Cancle and Return to home', root_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<h1 class="text-center mt-5"><%= "Category: " + @category.name %></h1>
<div class="row card-body justify-content-md-center">
  <% if logged_in? && current_user.admin? %>
    <span class="badge"><%= link_to "Edit category name", edit_category_path(@category) %></span>
  <% end %>
</div>
<%= render 'shared/pagination', obj: @category_articles %>
<%= render 'articles/article', obj: @category_articles %>
<%= render 'shared/pagination', obj: @category_articles %>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4 bg-dark text-white">
  <div class="container text-center">
	  <small>Copyright &copy; <%= link_to "Rob Gerrebrands", "https://de.linkedin.com/in/robgerrebrands", class: "text-white" %></small>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<div class="container">
	<% flash.each do |name, msg| %> 
		<div class="alert alert-success alert-dismissible fade show" role="alert">
			<%= msg %>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
	    	<span aria-hidden="true">&times;</span>
	  	</button>
	  </div>
	<% end %>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to "Alpha Blog", root_path, class: "navbar-brand", id: "logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

 <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Users", users_path , class: "nav-link" %>
      </li>
     <!--  <li class="nav-item">
      <%= link_to "Articles", articles_path , class: "nav-link" %>
      </li> -->
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Articles
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Articles", articles_path, class: "dropdown-item" %>
          <% if logged_in? %>
            <div class="dropdown-divider"></div>
            <%= link_to "New Article", new_article_path , class: "dropdown-item" %>
          <% end %>
        </div>
      </li>     
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Categories
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <%= link_to "All Categories", categories_path , class: "dropdown-item" %>
          <div class="dropdown-divider"></div>
          <% Category.all.each do |category| %>
            <%= link_to "#{category.name}", category_path(category) , class: "dropdown-item" %>
          <% end %>
          <%if logged_in? and current_user.admin? %>
            <div class="dropdown-divider"></div>
            <%= link_to "Create new Category", new_category_path , class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
      <% if logged_in? %>
        <li class="nav-item">
          <%= link_to current_user.username, user_path(current_user), class: "nav-link" %>
        </li>
      <% end %> 
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
    <ul class="nav navbar-nav navbar-right">   
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Your Profile <%= "Admin" if current_user.admin? %>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to "Edit Profile", edit_user_path(current_user) , class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "View Profile", user_path(current_user) , class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Log out', logout_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to 'Log in', login_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to 'Sign up', signup_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  </head>

  <body class="d-flex flex-column">
    
  <%= render 'layouts/navigation' %>
  <div id="page-content">
    <%= render 'layouts/messages' %>      
    <%= yield %>
  </div>
  <%= render 'layouts/footer' %>

  </body>
</html>

app/views/pages/about.html.erb
<h1>This is the About page</h1>
<p>These tags are inserted via autocomplete in Sublime.</p>

<%= link_to 'Go to the articles page', articles_path %> | 
<%= link_to 'Home page', root_path %>

app/views/pages/home.html.erb
<div class="container" id="home-container">
	<div class="jumbotron text-center text-white">
	  <h1 class="display-4">Alpha Blog!</h1>
	  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
	  <hr class="my-4">
	  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
	  <%= link_to "Sign Up!", signup_path, class: "btn btn-success btn-lg" %>
	  
	</div>
</div>

<!-- <p>Photo by Timothy Dykes on Unsplash</p> -->
<p>Photo by Rodion Kutsaev on Unsplash</p>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
	<div class="alert alert-danger alert-dismissible fade show" role="alert">
	  <h4 class="alert-heading">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h4>
	  <ul>
		  <% obj.errors.full_messages.each do |msg| %>
	  	<li><%= msg %></li>
	  	<% end %>
	  </ul>
	  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
   	 <span aria-hidden="true">&times;</span>
  	</button>
	</div>
<% end %>

app/views/shared/_pagination.html.erb
<div class="flickr_pagination mb-4">
	<%= will_paginate obj, :container => false %>
</div>

app/views/users/_form.html.erb
<div class="container">
  <%= render 'shared/errors', obj: @user %>
  <div class="row justify-content-center">
    <div class="col-10">
      <%= form_with(model: @user, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
        <div class="form-group row">
          <%= f.label :username, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.text_field :username, class: "form-control shadow rounded", placeholder: "Enter a username" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :email, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.email_field :email, class: "form-control shadow rounded", placeholder: "Enter an email address" %>
          </div>
        </div>

        <div class="form-group row">
          <%= f.label :password, class: "col-2 col-form-label text-light" %>
          <div class="col-sm-10">
            <%= f.password_field :password, class: "form-control shadow rounded", placeholder: "Choose a password" %>
          </div>
        </div>

        <div class="form-group row justify-content-center">
        <%= f.submit(@user.new_record? ? "Sign up" : "Update account" , class: "btn btn-outline-light btn-lg") %>
        </div>
      <% end %> 
    </div>
    <div class="mb-3">
    <%= link_to 'Cancle and Return to listing', articles_path, class: "text-info" %>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<h1 class="text-center mt-5">Edit Your profile</h1>

<%= render 'form' %>

app/views/users/index.html.erb
<h1 class="text-center mt-5">Users</h1>
<%= render 'shared/pagination', obj: @users %>
<div class="container">
	<% @users.each do |user| %>
		<div class="row justify-content-md-center">
			<div class="col-8 mt-4">
				<div class="card text-center shadow mb-5 bg-white rounded">
				  <div class="card-header font-italic">
				    <%= link_to user.username, user_path(user) %>
				  </div>
				  <div class="card-body">
				    <h5 class="card-title"><%= link_to gravatar_for(user, size: 150), user %></h5>
				    <p class="card-text"><%= pluralize(user.articles.count, "article") %></p>
				    <%= link_to "View profile", user_path(user), class: "btn btn-outline-success" %>
				    <% if logged_in? && (current_user == user || current_user.admin?) %>
				   	 <%= link_to "Edit profile", edit_user_path(user), class: "btn btn-outline-warning" %>
				    <% end %>
				    <% if logged_in? && current_user.admin? %>
				     <%= link_to "Delete this user", user_path(user), method: :delet, data: { confirm: "Are you sure you want to delete the user aand all their articles?" }, class: "btn btn-outline-danger" %>
				    <% end %>
				  </div>
				  <div class="card-footer text-muted">
				    <p><small>Joined: <%= user.created_at.strftime("%d %B %Y") %>, <%= time_ago_in_words(user.created_at) %> ago</small></p>
				  </div>
				</div>
			</div>
		</div>
	<% end %>
</div>
<%= render 'shared/pagination', obj: @users %>

app/views/users/new.html.erb
<h1 class="text-center mt-5">Sign Up Form</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1 class="text-center mt-4">Profile of <%= @user.username %></h1>

<%= gravatar_for @user, size: 200 %>
<br>
<div class="text-center mt-4">
	<% if logged_in? && current_user == @user || current_user.admin?%>
	<%= link_to "Edit your profile", edit_user_path(@user), class: "btn btn-outline-info" %></div>
	<% end %>

<h2 class="text-center mt-4">Articles from user</h2>
<%= render 'shared/pagination', obj: @user_articles %>
<%= render 'articles/article', obj: @user_articles %>
<%= render 'shared/pagination', obj: @user_articles %>


<%= link_to 'Return to listing', articles_path %>